select * from Customer limit 20;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT
    "Gender" AS gender,
    SUM("Purchase Amount (USD)") AS revenue
FROM Customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select "Customer ID" , "Purchase Amount (USD)" FROM Customer
Where "Discount Applied"='Yes'
AND "Purchase Amount (USD)">(SELECT AVG("Purchase Amount (USD)")
from Customer);

--Q3. Which are the top 5 products with the highest average review rating?
select "Item Purchased" ,ROUND(AVG("Review Rating"),2) as "Average Product Rating"
FROM Customer 
group by "Item Purchased"
order by AVG(Review Rating)desc
limit 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select "Shipping Type", ROUND(AVG("Purchase Amount (USD)"),2) AS avg_purcahse
from Customer
where "Shipping Type" IN ('Standard','Express')
group by "Shipping Type";

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select "Subscription Status",
       ROUND(AVG("Purchase Amount (USD)"),2) as average_spend,
	   SUM("Purchase Amount (USD)") as total_revenue
	   from Customer
	   group by "Subscription Status";

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select "Item Purchased", 
ROUND(100.0*SUM(CASE WHEN "Discount Applied"='Yes'then 1 else 0 end)
/Count(*),
2
) As discount_percentage
from Customer
group by "Item Purchased"
order by discount_percentage desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
CASE
    WHEN "Previous Purchases" = 0 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 1 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS customer_count
FROM Customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
SELECT
    "Category",
    "Item Purchased",
    purchase_count
FROM
(
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER
        (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM Customer
    GROUP BY "Category","Item Purchased"
) t
WHERE rn<=3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    "Subscription Status",
    COUNT(*) AS repeat_buyers
FROM Customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group?
SELECT
CASE
    WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
    WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
    WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
    WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
    ELSE '56+'
END AS age_group,
SUM("Purchase Amount (USD)") AS total_revenue
FROM Customer
GROUP BY age_group
ORDER BY total_revenue DESC;